#!/bin/python3
from sys import argv as __Arg__
from process import *
VERSSION="v1.0.4"
def __banner__(v):
    print("""\u001b[32m
╔═╗╔═╗╔═══╗╔═══╗ ╔═══╗╔══╗╔═╗─╔╗╔═══╗╔═══╗╔═══╗
║║╚╝║║║╔═╗║║╔═╗║ ║╔══╝╚╣─╝║║╚╗║║╚╗╔╗║║╔══╝║╔═╗║
║╔╗╔╗║║║─║║║║─╚╝ ║╚══╗─║║─║╔╗╚╝║─║║║║║╚══╗║╚═╝║
║║║║║║║╚═╝║║║─╔╗ ║╔══╝─║║─║║╚╗║║─║║║║║╔══╝║╔╗╔╝
║║║║║║║╔═╗║║╚═╝║ ║║───╔╣─╗║║─║║║╔╝╚╝║║╚══╗║║║╚╗
╚╝╚╝╚╝╚╝─╚╝╚═══╝ ╚╝───╚══╝╚╝─╚═╝╚═══╝╚═══╝╚╝╚═╝\u001b[0m
...:::::::::::[\u001b[41mPython Mac Finder\u001b[0m]:::::::::::...  (\u001b[33;1m{}\u001b[0m)""".format(v))
def __help1__():
    print("Usage:")
    print("         python3 macfinder [-h] [-a] <MACID>")
    print()
try:
    b=__Arg__[1]
except:
    __help1__()
def mac(A,b):
    _op3_=""
    for i in A:
        if b.upper() in A[i]:
            _op1_=b1[0:2]+":"+b1[2:4]+":"+b1[4:6]
            _op3_=str(A[i])
            _op3_=_op3_[7:]
            _print_(_op1_,_op2_,_op3_)
    if _op3_ == "":
        print("[\u001b[33;1m!\u001b[0m] Not Found !")
def _print_(_op1_,_op2_,_op3_):
    __len__=len(_op3_)
    _min_="-"
    _spc_=" "
    _spc_*=__len__
    _min_*=__len__
    _op_="\u001b[32m"+_op1_+"\u001b[0m"+_op2_
    print("""+-------------------+----------{__min__}-+
|        \u001b[31;1mMac\u001b[0m        |     \u001b[31;1mVendor\u001b[0m{__spc__}|
+-------------------+----------{__min__}-+
| {:^19} |  {}         |
+-------------------+----------{__min__}-+""".format(_op_,_op3_,__min__=_min_,__spc__=_spc_,__Len__=int(__len__)))

def __help2__(v):
    __banner__(v)
    print("""
Macfinder shows vendor  of  The Mac address  

\u001b[31;4mUsage\u001b[0m:
        macfinder \u001b[2;1m[-h] [-a] \u001b[0m<MAC_ID>  

\u001b[31;4mArgs\u001b[0m:
        -a  --about    About

       \u001b[2;1m -h  --help\u001b[0m     This banner

       \u001b[2;1mIt Find the given mac address's vendor only.But not the hole divice's model.Mac address is the six pares of Two value are seperated by a colen.For example 'd0:67:e5:17:6A:51' like this.In Mac address the first three pare is denote as The vendor of the mac address.

\u001b[34;1mFrom ::: Red-5-crackers ::: https://github.com/RED-5-CRACKERS/Mac_finder.git\u001b[0m 
""")
def __about__(v):
    __banner__(v)
    print("""
-------------({G}INFO{N})---------------
[{R}*{N}] Name    : Macfinder
[{R}*{N}] Code    : {G}Python3.7{N}
[{R}*{N}] Verssion: ({Y}{V}{N})
[{R}*{N}] Auther  : Madhava
[{R}*{N}] Org     : {R}Red-5-crackers{N}
[{R}*{N}] Link    : {G1}https://git.io/JvAiL{N}
----------------------------------
            """.format(R="\u001b[31m",N="\u001b[0m",Y="\u001b[33;1m",G="\u001b[32m",G1="\u001b[32;4;1m",V=v))
if True:
    try:
        if len(b)==12:
            b=list(b)
            b.insert(2,":")
            b.insert(5,":")
            b.insert(8,":")
            b.insert(-5,":")
            b.insert(-2,":")
            b="".join(b)
        if len(b)==17:
            if "-" in list(b):
                b=b.replace("-",":")
            if " " in list(b):
                b=b.replace(" ",":")
        if len(b)==6:
            b=list(b)
            b.insert(2,":")
            b.insert(5,":")
            b="".join(b)+":00:00:00"
        if len(b)==8:
            if ":" in list(b):
                pass
            if "-" in list(b):
                b=b.replace("-",":")
            b=b+":00:00:00"
    except:
        pass
try:
    if len(b) == 17:
        b=b.split(":")
        b="".join(b)
        b1=b[0:6]
        b2=b[6:13]
        _op2_=":"+b2[0:2]+":"+b2[2:4]+":"+b2[4:6]
        mac(A,b1)
    elif len(b) != 17 and b != "" and b != "-h" and b != "--help" and b != "--about" and b != "-a":
        print("\u001b[32;1mOops..!\u001b[0m, Invalied Address [ \u001b[31;1m{}\u001b[0m ]".format(b))
except:
    pass
def __opt__(b,v):
    if b == "-a" or b == "--about":
        __about__(v)
    if b == "" or b == "-h" or b == "--help":
        __help2__(v)
try:
    if __Arg__[2] != None:
        __opt__(b)
        __opt__(__Arg__[2])
except:
    try:
        __opt__(b,VERSSION)
    except:
        pass
