#!/bin/bash
python3 -c "print(u'\u001b[32;1m')"
echo "What's the thing inside setup ?"
sleep 1.3
cat setup
chmod +x macfinder
function Termux(){
  if [ -e /data/data/com.termux/files/usr/share/macfinder/macfinder ]
	then
		cp macfinder /data/data/com.termux/files/usr/share/macfinder/bin/macfinder
    		chmod +x /data/data/com.termux/files/usr/share/macfinder/macfinder	
	else
		mkdir /data/data/com.termux/files/usr/share/macfinder/
		cp macfinder /data/data/com.termux/files/usr/share/macfinder/macfinder
		chmod +x /data/data/com.termux/files/usr/share/macfinder/macfinder
		chmod +x macfinder
    		cp process.py /data/data/com.termux/files/usr/share/macfinder/process.py
		echo "cd /data/data/com.termux/files/usr/share/macfinder/ && ./macfinder"
	fi
	if [ -e /data/data/com.termux/files/usr/bin/python3 ]
	then
		a='a'
	else
		
		pkg install python3
	fi
}
function Linux(){
	if [ -e /usr/share/macfinder ]
	then 
		chmod +x macfinder
    		cp macfinder /usr/share/macfinder/macfinder
    		chmod +x /usr/share/macfinder/macfinder
    		cp process.py /usr/share/macfinder/process.py
	else
		echo "cd /usr/share/macfinder/ && ./macfinder" > /use/bin/macfinder
		mkdir /usr/share/macfinder
    		chmod +x macfinder
    		cp macfinder /usr/share/macfinder/macfinder
    		chmod +x /usr/share/macfinder/macfinder
    		cp process.py /usr/share/macfinder/process.py		
	fi
}
function Main(){
	echo "===================================="
	echo "From R-5-C:"
	echo ""
	echo "•----------------------------------•"
	echo "|                                  |"
	echo "|   [1] Setup for Linux            |"
	echo "|   [2] Setup for Termux           |"
	echo "|                                  |"
	echo "•----------------------------------•"
	echo ""
	echo -n "Select any one of these > "
	read option
	python3 -c "print(u'\u001b[31;1m')"	
	if [ $option = "1" ]
	then
		python3 -c "print(u'\u001b[31;1m')"
		Linux
	fi

	if [ $option = "2" ]
	then
		python3 -c "print(u'\u001b[31;1m')"
		Termux
	fi
	python3 -c "print(u'\u001b[33;1m')"
	
	sleep 2
	
	python3 -c "print(u'\u001b[0m')"
	echo " [*] Rerun “./setup” while error occered"
	echo " [*] Simply type macfinder"
}
Main
